//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int carritoId { get; set; }
        public int usuarioId { get; set; }
        public int productoId { get; set; }
        public int pedidoCantidad { get; set; }
        public double pedidoSubtotal { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual usuario usuario { get; set; }

        internal object ToList()
        {
            throw new NotImplementedException();
        }
    }
}
