//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public int idOrden { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> productoId { get; set; }
        public Nullable<int> ordenCantidad { get; set; }
        public Nullable<double> ordenTotal { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
