//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int pedidoId { get; set; }
        public Nullable<int> ordenId { get; set; }
        public Nullable<int> productoId { get; set; }
        public Nullable<int> pedidoCantidad { get; set; }
        public Nullable<double> pedidoSubtotal { get; set; }
    
        public virtual orden orden { get; set; }
        public virtual producto producto { get; set; }
    }
}
