//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int pedidoId { get; set; }
        public Nullable<int> ordenId { get; set; }
        public Nullable<int> productoId { get; set; }
        public Nullable<int> pedidoCantidad { get; set; }
        public Nullable<double> pedidoSubtotal { get; set; }
    
        public virtual orden orden { get; set; }
        public virtual producto producto { get; set; }
    }
}
