//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.ordens = new HashSet<orden>();
        }
    
        public int productoId { get; set; }
        public string productoNombre { get; set; }
        public Nullable<double> productoPrecio { get; set; }
        public Nullable<int> productoExistencia { get; set; }
        public Nullable<int> categoriaId { get; set; }
        public Nullable<int> subcategoriaId { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> ordens { get; set; }
        public virtual subcategoria subcategoria { get; set; }
    }
}
